### ISSUE TITLE
SpatialiteInit.h not being used

### ISSUE THREAD

**Issue by hallahan** [amigocloud/amigoclient#745]
Searching around the project, it looks like `SpatialiteInit.h` in the actual amigo core is not being used. Database.cpp [includes it](https://github.com/amigocloud/amigoclient/blob/b8372580d7fe592d59c7874cc450537c1077cfaf/core/src/AmigoCore/core/Database.cpp#L32), but the SQL function that is added as part of Spatialite is [being used instead](https://github.com/amigocloud/amigoclient/blob/b8372580d7fe592d59c7874cc450537c1077cfaf/core/src/AmigoCore/core/Database.cpp#L113).

```cpp
if(_isSpatial)
{
	_cache = spatialite_alloc_connection ();
	spatialite_init_ex(_pDatabase, _cache, 0);
	if (!fileExists)
	{
		_executeSQLInternal("SELECT InitSpatialMetaData('NONE')");
		_executeSQLInternal("SELECT InsertEpsgSrid(4326)");
	}
}
```

Perhaps `SpatialiteInit` should be removed from the project?

**Comment by vchernetsky** [comment]
It get's called from inside spatialite.
