### ISSUE TITLE
Add callback to obtain form information

### ISSUE THREAD

**Issue by alculquicondor** [amigocloud/amigoclient#782]
Endpoints are described here:
https://github.com/amigocloud/amigoserver/wiki/Forms-API#endpoints

Callback prototype:
```js
AmigoPlatform.getForm = function (datasetId, type)
```

Only the form information itself is needed (no overridden flag)

**Comment by vchernetsky** [comment]
What should this call back return?

**Comment by alculquicondor** [comment]
The json describing the form from the endpoint
